// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvmoxaunxhpipqaxjurx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bW94YXVueGhwaXBxYXhqdXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDI4NTksImV4cCI6MjA2ODc3ODg1OX0.xUoFOS0NmvTTNkFW__xJhq7jETDKVh42ftcLmKzfAvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});